
// This file has been generated by the GUI designer. Do not modify.
namespace LeaseAgreement
{
	public partial class PlanViewWidget
	{
		private global::Gtk.Table table1;
		
		private global::Gamma.Widgets.ySpecComboBox comboBoxFloor;
		
		private global::Gtk.DrawingArea drawingarea1;
		
		private global::Gtk.HScrollbar hscrollbar1;
		
		private global::Gtk.VScrollbar vscrollbar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LeaseAgreement.PlanViewWidget
			global::Stetic.BinContainer.Attach (this);
			this.WidthRequest = 400;
			this.HeightRequest = 300;
			this.Sensitive = false;
			this.Name = "LeaseAgreement.PlanViewWidget";
			// Container child LeaseAgreement.PlanViewWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.comboBoxFloor = new global::Gamma.Widgets.ySpecComboBox ();
			this.comboBoxFloor.Name = "comboBoxFloor";
			this.comboBoxFloor.AddIfNotExist = false;
			this.comboBoxFloor.ShowSpecialStateAll = false;
			this.comboBoxFloor.ShowSpecialStateNot = true;
			this.table1.Add (this.comboBoxFloor);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboBoxFloor]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.drawingarea1 = new global::Gtk.DrawingArea ();
			this.drawingarea1.CanFocus = true;
			this.drawingarea1.Events = ((global::Gdk.EventMask)(2098948));
			this.drawingarea1.Name = "drawingarea1";
			this.table1.Add (this.drawingarea1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.drawingarea1]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.hscrollbar1 = new global::Gtk.HScrollbar (null);
			this.hscrollbar1.Name = "hscrollbar1";
			this.hscrollbar1.Adjustment.Upper = 100D;
			this.hscrollbar1.Adjustment.PageIncrement = 10D;
			this.hscrollbar1.Adjustment.PageSize = 10D;
			this.hscrollbar1.Adjustment.StepIncrement = 1D;
			this.hscrollbar1.Adjustment.Value = 20D;
			this.table1.Add (this.hscrollbar1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.hscrollbar1]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vscrollbar1 = new global::Gtk.VScrollbar (null);
			this.vscrollbar1.Name = "vscrollbar1";
			this.vscrollbar1.Adjustment.Upper = 100D;
			this.vscrollbar1.Adjustment.PageIncrement = 10D;
			this.vscrollbar1.Adjustment.PageSize = 10D;
			this.vscrollbar1.Adjustment.StepIncrement = 1D;
			this.table1.Add (this.vscrollbar1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.vscrollbar1]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.vscrollbar1.ValueChanged += new global::System.EventHandler (this.OnVscrollbar1ValueChanged);
			this.hscrollbar1.ValueChanged += new global::System.EventHandler (this.OnHscrollbar1ValueChanged);
			this.drawingarea1.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawingAreaExposed);
			this.drawingarea1.ScrollEvent += new global::Gtk.ScrollEventHandler (this.OnDrawingAreaScroll);
			this.drawingarea1.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnDrawingAreaSizeAllocated);
			this.drawingarea1.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnButtonPressed);
			this.drawingarea1.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnButtonReleased);
			this.drawingarea1.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnPointerMotion);
			this.comboBoxFloor.Changed += new global::System.EventHandler (this.OnComboBoxFloorChanged);
		}
	}
}
