
// This file has been generated by the GUI designer. Do not modify.
namespace LeaseAgreement
{
	public partial class Contract
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Notebook notebookMain;
		
		private global::Gtk.HBox hboxInfo;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.CheckButton checkDraft;
		
		private global::Gtk.ComboBox comboContractType;
		
		private global::Gtk.ComboBox comboOrg;
		
		private global::QSWidgetLib.DatePicker datepickerSign;
		
		private global::Gtk.Entry entryNumber;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Entry entryLessee;
		
		private global::Gtk.Button buttonLesseeOpen;
		
		private global::Gtk.Button buttonLesseeEdit;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.ComboBox comboPlaceT;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ComboBox comboPlaceNo;
		
		private global::Gtk.Label labelArea;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Table table3;
		
		private global::QSWidgetLib.DatePicker datepickerCancel;
		
		private global::QSWidgetLib.DatePicker datepickerEnd;
		
		private global::QSWidgetLib.DatePicker datepickerStart;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment8;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textComments;
		
		private global::Gtk.Label GtkLabel9;
		
		private global::Gtk.Label label2;
		
		private global::QSCustomFields.CustomFields customContracts;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.VBox vboxDocs;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView treeviewDocs;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Button buttonPrint;
		
		private global::Gtk.Button buttonEdit;
		
		private global::Gtk.Button buttonRemove;
		
		private global::Gtk.Label label4;
		
		private global::QSAttachment.Attachment attachmentFiles;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LeaseAgreement.Contract
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "LeaseAgreement.Contract";
			this.Title = global::Mono.Unix.Catalog.GetString ("Новый договор");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child LeaseAgreement.Contract.VBox
			global::Gtk.VBox w2 = this.VBox;
			w2.Name = "dialog1_VBox";
			w2.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebookMain = new global::Gtk.Notebook ();
			this.notebookMain.CanFocus = true;
			this.notebookMain.Name = "notebookMain";
			this.notebookMain.CurrentPage = 2;
			this.notebookMain.TabPos = ((global::Gtk.PositionType)(0));
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.hboxInfo = new global::Gtk.HBox ();
			this.hboxInfo.Name = "hboxInfo";
			this.hboxInfo.Spacing = 6;
			// Container child hboxInfo.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.checkDraft = new global::Gtk.CheckButton ();
			this.checkDraft.CanFocus = true;
			this.checkDraft.Name = "checkDraft";
			this.checkDraft.Label = global::Mono.Unix.Catalog.GetString ("Черновик");
			this.checkDraft.DrawIndicator = true;
			this.checkDraft.UseUnderline = true;
			this.table2.Add (this.checkDraft);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkDraft]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.comboContractType = new global::Gtk.ComboBox ();
			this.comboContractType.Name = "comboContractType";
			this.table2.Add (this.comboContractType);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.comboContractType]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.comboOrg = new global::Gtk.ComboBox ();
			this.comboOrg.Name = "comboOrg";
			this.table2.Add (this.comboOrg);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.comboOrg]));
			w5.TopAttach = ((uint)(4));
			w5.BottomAttach = ((uint)(5));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.datepickerSign = new global::QSWidgetLib.DatePicker ();
			this.datepickerSign.Events = ((global::Gdk.EventMask)(256));
			this.datepickerSign.Name = "datepickerSign";
			this.datepickerSign.Date = new global::System.DateTime (0);
			this.datepickerSign.IsEditable = true;
			this.datepickerSign.AutoSeparation = true;
			this.table2.Add (this.datepickerSign);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.datepickerSign]));
			w6.TopAttach = ((uint)(6));
			w6.BottomAttach = ((uint)(7));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryNumber = new global::Gtk.Entry ();
			this.entryNumber.CanFocus = true;
			this.entryNumber.Name = "entryNumber";
			this.entryNumber.IsEditable = true;
			this.entryNumber.MaxLength = 15;
			this.entryNumber.InvisibleChar = '•';
			this.table2.Add (this.entryNumber);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryNumber]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryLessee = new global::Gtk.Entry ();
			this.entryLessee.CanFocus = true;
			this.entryLessee.Name = "entryLessee";
			this.entryLessee.IsEditable = false;
			this.entryLessee.InvisibleChar = '•';
			this.hbox1.Add (this.entryLessee);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entryLessee]));
			w8.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonLesseeOpen = new global::Gtk.Button ();
			this.buttonLesseeOpen.TooltipMarkup = "Открыть текущего арендатора";
			this.buttonLesseeOpen.Sensitive = false;
			this.buttonLesseeOpen.CanFocus = true;
			this.buttonLesseeOpen.Name = "buttonLesseeOpen";
			this.buttonLesseeOpen.UseUnderline = true;
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			this.buttonLesseeOpen.Image = w9;
			this.hbox1.Add (this.buttonLesseeOpen);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonLesseeOpen]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonLesseeEdit = new global::Gtk.Button ();
			this.buttonLesseeEdit.TooltipMarkup = "Изменить арендатора";
			this.buttonLesseeEdit.CanFocus = true;
			this.buttonLesseeEdit.Name = "buttonLesseeEdit";
			this.buttonLesseeEdit.UseUnderline = true;
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.buttonLesseeEdit.Image = w11;
			this.hbox1.Add (this.buttonLesseeEdit);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonLesseeEdit]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.table2.Add (this.hbox1);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox1]));
			w13.TopAttach = ((uint)(5));
			w13.BottomAttach = ((uint)(6));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboPlaceT = new global::Gtk.ComboBox ();
			this.comboPlaceT.Name = "comboPlaceT";
			this.hbox5.Add (this.comboPlaceT);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.comboPlaceT]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("-");
			this.hbox5.Add (this.label1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label1]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboPlaceNo = global::Gtk.ComboBox.NewText ();
			this.comboPlaceNo.Name = "comboPlaceNo";
			this.hbox5.Add (this.comboPlaceNo);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.comboPlaceNo]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.labelArea = new global::Gtk.Label ();
			this.labelArea.TooltipMarkup = "Площадь";
			this.labelArea.Name = "labelArea";
			this.labelArea.UseMarkup = true;
			this.hbox5.Add (this.labelArea);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.labelArea]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 3;
			w17.Fill = false;
			this.table2.Add (this.hbox5);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox5]));
			w18.TopAttach = ((uint)(3));
			w18.BottomAttach = ((uint)(4));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Статус:");
			this.table2.Add (this.label10);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2 [this.label10]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 1F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Тип договора:");
			this.table2.Add (this.label14);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.label14]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Номер договора<span foreground=\"red\">*</span>:");
			this.label5.UseMarkup = true;
			this.table2.Add (this.label5);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Организация<span foreground=\"red\">*</span>:");
			this.label6.UseMarkup = true;
			this.table2.Add (this.label6);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
			w22.TopAttach = ((uint)(4));
			w22.BottomAttach = ((uint)(5));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Место<span foreground=\"red\">*</span>:");
			this.label7.UseMarkup = true;
			this.table2.Add (this.label7);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2 [this.label7]));
			w23.TopAttach = ((uint)(3));
			w23.BottomAttach = ((uint)(4));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Арендатор<span foreground=\"red\">*</span>:");
			this.label8.UseMarkup = true;
			this.table2.Add (this.label8);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2 [this.label8]));
			w24.TopAttach = ((uint)(5));
			w24.BottomAttach = ((uint)(6));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата подписания:");
			this.table2.Add (this.label9);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2 [this.label9]));
			w25.TopAttach = ((uint)(6));
			w25.BottomAttach = ((uint)(7));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hboxInfo.Add (this.table2);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hboxInfo [this.table2]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hboxInfo.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.datepickerCancel = new global::QSWidgetLib.DatePicker ();
			this.datepickerCancel.Events = ((global::Gdk.EventMask)(256));
			this.datepickerCancel.Name = "datepickerCancel";
			this.datepickerCancel.Date = new global::System.DateTime (0);
			this.datepickerCancel.IsEditable = true;
			this.datepickerCancel.AutoSeparation = true;
			this.table3.Add (this.datepickerCancel);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table3 [this.datepickerCancel]));
			w27.TopAttach = ((uint)(2));
			w27.BottomAttach = ((uint)(3));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.datepickerEnd = new global::QSWidgetLib.DatePicker ();
			this.datepickerEnd.Events = ((global::Gdk.EventMask)(256));
			this.datepickerEnd.Name = "datepickerEnd";
			this.datepickerEnd.Date = new global::System.DateTime (0);
			this.datepickerEnd.IsEditable = true;
			this.datepickerEnd.AutoSeparation = true;
			this.table3.Add (this.datepickerEnd);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table3 [this.datepickerEnd]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.datepickerStart = new global::QSWidgetLib.DatePicker ();
			this.datepickerStart.Events = ((global::Gdk.EventMask)(256));
			this.datepickerStart.Name = "datepickerStart";
			this.datepickerStart.Date = new global::System.DateTime (0);
			this.datepickerStart.IsEditable = true;
			this.datepickerStart.AutoSeparation = true;
			this.table3.Add (this.datepickerStart);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table3 [this.datepickerStart]));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата начала аренды<span foreground=\"red\">*</span>:");
			this.label11.UseMarkup = true;
			this.table3.Add (this.label11);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table3 [this.label11]));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата окончания аренды<span foreground=\"red\">*</span>:");
			this.label12.UseMarkup = true;
			this.table3.Add (this.label12);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table3 [this.label12]));
			w31.TopAttach = ((uint)(1));
			w31.BottomAttach = ((uint)(2));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 1F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата расторжения:");
			this.table3.Add (this.label13);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table3 [this.label13]));
			w32.TopAttach = ((uint)(2));
			w32.BottomAttach = ((uint)(3));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.table3);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table3]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment8 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment8.Name = "GtkAlignment8";
			this.GtkAlignment8.LeftPadding = ((uint)(12));
			// Container child GtkAlignment8.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textComments = new global::Gtk.TextView ();
			this.textComments.CanFocus = true;
			this.textComments.Name = "textComments";
			this.textComments.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.textComments);
			this.GtkAlignment8.Add (this.GtkScrolledWindow);
			this.frame1.Add (this.GtkAlignment8);
			this.GtkLabel9 = new global::Gtk.Label ();
			this.GtkLabel9.Name = "GtkLabel9";
			this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Комментарии</b>");
			this.GtkLabel9.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel9;
			this.vbox3.Add (this.frame1);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame1]));
			w37.Position = 1;
			this.hboxInfo.Add (this.vbox3);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hboxInfo [this.vbox3]));
			w38.Position = 1;
			this.notebookMain.Add (this.hboxInfo);
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Информация");
			this.notebookMain.SetTabLabel (this.hboxInfo, this.label2);
			this.label2.ShowAll ();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.customContracts = new global::QSCustomFields.CustomFields ();
			this.customContracts.Events = ((global::Gdk.EventMask)(256));
			this.customContracts.Name = "customContracts";
			this.customContracts.ObjectId = -1;
			this.notebookMain.Add (this.customContracts);
			global::Gtk.Notebook.NotebookChild w40 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain [this.customContracts]));
			w40.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Дополнительно");
			this.notebookMain.SetTabLabel (this.customContracts, this.label3);
			this.label3.ShowAll ();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.vboxDocs = new global::Gtk.VBox ();
			this.vboxDocs.Name = "vboxDocs";
			this.vboxDocs.Spacing = 6;
			// Container child vboxDocs.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Печатные формы документов для договора.");
			this.vboxDocs.Add (this.label16);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vboxDocs [this.label16]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vboxDocs.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeviewDocs = new global::Gtk.TreeView ();
			this.treeviewDocs.CanFocus = true;
			this.treeviewDocs.Name = "treeviewDocs";
			this.GtkScrolledWindow1.Add (this.treeviewDocs);
			this.vboxDocs.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vboxDocs [this.GtkScrolledWindow1]));
			w43.Position = 1;
			// Container child vboxDocs.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonPrint = new global::Gtk.Button ();
			this.buttonPrint.Sensitive = false;
			this.buttonPrint.CanFocus = true;
			this.buttonPrint.Name = "buttonPrint";
			this.buttonPrint.UseUnderline = true;
			this.buttonPrint.Label = global::Mono.Unix.Catalog.GetString ("Распечатать");
			global::Gtk.Image w44 = new global::Gtk.Image ();
			w44.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Menu);
			this.buttonPrint.Image = w44;
			this.hbox8.Add (this.buttonPrint);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.buttonPrint]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonEdit = new global::Gtk.Button ();
			this.buttonEdit.TooltipMarkup = "Редактировать шаблон только для этого договора.";
			this.buttonEdit.Sensitive = false;
			this.buttonEdit.CanFocus = true;
			this.buttonEdit.Name = "buttonEdit";
			this.buttonEdit.UseUnderline = true;
			this.buttonEdit.Label = global::Mono.Unix.Catalog.GetString ("Редактировать");
			global::Gtk.Image w46 = new global::Gtk.Image ();
			w46.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.buttonEdit.Image = w46;
			this.hbox8.Add (this.buttonEdit);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.buttonEdit]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonRemove = new global::Gtk.Button ();
			this.buttonRemove.Sensitive = false;
			this.buttonRemove.CanFocus = true;
			this.buttonRemove.Name = "buttonRemove";
			this.buttonRemove.UseUnderline = true;
			this.buttonRemove.Label = global::Mono.Unix.Catalog.GetString ("Вернуть шаблон");
			global::Gtk.Image w48 = new global::Gtk.Image ();
			w48.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.buttonRemove.Image = w48;
			this.hbox8.Add (this.buttonRemove);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.buttonRemove]));
			w49.Position = 2;
			w49.Expand = false;
			w49.Fill = false;
			this.vboxDocs.Add (this.hbox8);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vboxDocs [this.hbox8]));
			w50.Position = 2;
			w50.Expand = false;
			w50.Fill = false;
			this.notebookMain.Add (this.vboxDocs);
			global::Gtk.Notebook.NotebookChild w51 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain [this.vboxDocs]));
			w51.Position = 2;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Документы");
			this.notebookMain.SetTabLabel (this.vboxDocs, this.label4);
			this.label4.ShowAll ();
			// Container child notebookMain.Gtk.Notebook+NotebookChild
			this.attachmentFiles = new global::QSAttachment.Attachment ();
			this.attachmentFiles.Events = ((global::Gdk.EventMask)(256));
			this.attachmentFiles.Name = "attachmentFiles";
			this.notebookMain.Add (this.attachmentFiles);
			global::Gtk.Notebook.NotebookChild w52 = ((global::Gtk.Notebook.NotebookChild)(this.notebookMain [this.attachmentFiles]));
			w52.Position = 3;
			// Notebook tab
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Файлы");
			this.notebookMain.SetTabLabel (this.attachmentFiles, this.label15);
			this.label15.ShowAll ();
			w2.Add (this.notebookMain);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(w2 [this.notebookMain]));
			w53.Position = 0;
			// Internal child LeaseAgreement.Contract.ActionArea
			global::Gtk.HButtonBox w54 = this.ActionArea;
			w54.Name = "dialog1_ActionArea";
			w54.Spacing = 10;
			w54.BorderWidth = ((uint)(5));
			w54.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("О_тменить");
			global::Gtk.Image w55 = new global::Gtk.Image ();
			w55.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w55;
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w56 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w54 [this.buttonCancel]));
			w56.Expand = false;
			w56.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.Sensitive = false;
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString ("_OK");
			global::Gtk.Image w57 = new global::Gtk.Image ();
			w57.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Menu);
			this.buttonOk.Image = w57;
			w54.Add (this.buttonOk);
			global::Gtk.ButtonBox.ButtonBoxChild w58 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w54 [this.buttonOk]));
			w58.Position = 1;
			w58.Expand = false;
			w58.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 850;
			this.DefaultHeight = 383;
			this.Show ();
			this.comboPlaceT.Changed += new global::System.EventHandler (this.OnComboPlaceTChanged);
			this.comboPlaceNo.Changed += new global::System.EventHandler (this.OnComboPlaceNoChanged);
			this.buttonLesseeOpen.Clicked += new global::System.EventHandler (this.OnButtonLesseeOpenClicked);
			this.buttonLesseeEdit.Clicked += new global::System.EventHandler (this.OnButtonLesseeEditClicked);
			this.entryNumber.Changed += new global::System.EventHandler (this.OnEntryNumberChanged);
			this.entryNumber.Activated += new global::System.EventHandler (this.OnEntryActivated);
			this.comboOrg.Changed += new global::System.EventHandler (this.OnComboOrgChanged);
			this.comboContractType.Changed += new global::System.EventHandler (this.OnComboContractTypeChanged);
			this.datepickerStart.DateChanged += new global::System.EventHandler (this.OnDatepickerStartDateChanged);
			this.datepickerEnd.DateChanged += new global::System.EventHandler (this.OnDatepickerEndDateChanged);
			this.datepickerCancel.DateChanged += new global::System.EventHandler (this.OnDatepickerCancelDateChanged);
			this.treeviewDocs.CursorChanged += new global::System.EventHandler (this.OnTreeviewDocsCursorChanged);
			this.treeviewDocs.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeviewDocsRowActivated);
			this.buttonPrint.Clicked += new global::System.EventHandler (this.OnButtonPrintClicked);
			this.buttonRemove.Clicked += new global::System.EventHandler (this.OnButtonRemoveClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
